### ISSUE TITLE
[BUG] Problème sendpush

### ISSUE THREAD

**Issue by prohand** [jeromedevel/droideon#1]
Bonjour,

J'ai un problème avec sendpush, quand je le lance, il me mets : 
./sendpush: ▒▒  ▒       h▒cO▒▒▒▒2▒Alocation has changed!

Avez-vous une solution ?

Merci

Version 18.10 de Centreon

**Comment by jeromedevel** [comment]
Bonjour,

vous êtes sur centos 7 ?

**Comment by prohand** [comment]
> Bonjour,
> 
> vous êtes sur centos 7 ?

Oui, CentOS Linux release 7.6.1810

**Comment by markus07** [comment]
The same problem ./sendpush: c▒▒▒j▒g▒▒+▒or▒Alocation has changed!

CentOS Linux release 7.6.1810 (Core)

Linux localhost 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jeromedevel** [comment]
new version for sendpush, it's a python version 
you should install python-requests
and add "python" at the begining of command

**Comment by prohand** [comment]
Thank you.
The new plugin solved my problem.
