### ISSUE TITLE
[FEATURE] Ajouter plusieurs serveurs

### ISSUE THREAD

**Issue by prohand** [jeromedevel/droideon#3]
Bonjour,

Il serait vraiment bien, si dans une version future nous puissions ajouter plusieurs serveurs.

Merci

**Comment by jeromedevel** [comment]
bonjour,

le design de l'application ne permet pas d'avoir plusieurs serveurs, il faut mettre plusieurs poller sinon.

**Comment by prohand** [comment]
Bonjour,

Merci pour le retour,
Dans mon cas c'était pouvoir rajouter le centreon de mon travail + mon perso.

**Comment by jeromedevel** [comment]
développement en cours

**Comment by prohand** [comment]
Merci :)

**Comment by jeromedevel** [comment]
ajouté en 1.3

**Comment by prohand** [comment]
Merci ;)
