### ISSUE TITLE
Connexion impossible 19.10.x

### ISSUE THREAD

**Issue by prohand** [jeromedevel/droideon#5]
Bonjour,

Depuis la mise à jour en 19.10 il est impossible de se connecter à centreon via l'application.
J'ai ce problème sur 2 serveurs différents.

Merci

**Comment by jeromedevel** [comment]
a cause de https://github.com/centreon/centreon/pull/7892
j'essaie de trouver une solution de contournement

**Comment by jeromedevel** [comment]
fixed in 1.3.2

**Comment by prohand** [comment]
Merci ;)
