### ISSUE TITLE
Chargement impossible depuis 19.10.4

### ISSUE THREAD

**Issue by prohand** [jeromedevel/droideon#7]
Bonjour,

Depuis la version 19.10.4 de centreon web, il est possible de se connecter par contre il reste bloqué avec un rond qui tourne et ne charge aucun hote et service.

Si besoin je pourrais fournir des logs ;)

Merci

**Comment by maxdevaine** [comment]
Hello,
I have same problem.
Centreon version: 19.10.6
DroidEon version: 1.3.2

Change auth type between token and password not helping.

httpd24 logs :
[Tue Feb 04 14:56:24.988947 2020] [proxy_fcgi:error] [pid 15876] [client 192.168.80.1:49769] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 04 14:56:25.878944 2020] [proxy_fcgi:error] [pid 15939] [client 192.168.80.1:49772] AH01071: Got error 'Primary script unknown\n'
[Tue Feb 04 14:56:26.067164 2020] [proxy_fcgi:error] [pid 18034] [client 192.168.80.1:49773] AH01071: Got error 'Primary script unknown\n'

Auth works :
2020-02-04 14:57:45|20|0|0|[WEB] [192.168.80.1] Authentication succeeded for 'devaine'

Thanks
Max

**Comment by jeromedevel** [comment]
#6  same issue

**Comment by jeromedevel** [comment]
version 1.3.3 correct this bug
